config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins

  resources :transactions, only: %i[index show]
  resources :merchants, only: %i[index show destroy]
  resources :merchant_customizations, only: %i[new create]

  namespace :api do
    namespace :v1 do
      resources :transactions, only: :create
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  devise :database_authenticatable, :timeoutable, :validatable

  # additional checks of email format
  validates_with EmailAddress::ActiveRecordValidator
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/has_uuid.rb
# frozen_string_literal: true

module HasUuid
  extend ActiveSupport::Concern

  included do
    # postgres convert uuid to downcase
    # rails validates a content of the uuid type, set it to nil if its value is invalid
    validates :uuid, uniqueness: { case_sensitive: false }
    validates :uuid, presence: true

    after_initialize :initialize_uuid
  end

  private

  def initialize_uuid
    self.uuid ||= Digest::UUID.uuid_v4
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  devise :database_authenticatable, :timeoutable, :validatable

  enum status: { inactive: 0, active: 1 }

  validates :total_transaction_sum, numericality: { greater_than_or_equal_to: 0 }
  validates :status, presence: true
  # additional checks of email format
  validates_with EmailAddress::ActiveRecordValidator

  has_many :transactions, class_name: 'Transaction::Base', dependent: :destroy
end

app/models/transaction.rb
# frozen_string_literal: true

module Transaction
  def self.table_name_prefix
    'transaction_'
  end
end

app/models/transaction/authorization.rb
# frozen_string_literal: true

module Transaction
  class Authorization < Base
    validates :customer_email, presence: true
    validates_with EmailAddress::ActiveRecordValidator, field: :customer_email
    validates :amount, numericality: { greater_than: 0 }

    belongs_to :merchant
  end
end

app/models/transaction/base.rb
# frozen_string_literal: true

module Transaction
  class Base < ApplicationRecord
    include HasUuid

    self.table_name = 'transactions'

    enum status: { approved: 0, reversed: 1, refunded: 2, error: 3 }

    validates :status, presence: true

    belongs_to :previous_transaction, class_name: 'Transaction::Base', optional: true
  end
end

app/models/transaction/charge.rb
# frozen_string_literal: true

module Transaction
  class Charge < Base
    validates :amount, numericality: { greater_than: 0 }
  end
end

app/models/transaction/refund.rb
# frozen_string_literal: true

module Transaction
  class Refund < Base
    validates :amount, numericality: { greater_than: 0 }
  end
end

app/models/transaction/reverse.rb
# frozen_string_literal: true

module Transaction
  class Reverse < Base
  end
end

app/controllers/api/v1/transactions_controller.rb
# frozen_string_literal: true

module Api
  # :reek:UncommunicativeModuleName
  module V1
    class TransactionsController < ApplicationController
      skip_before_action :verify_authenticity_token

      http_basic_authenticate_with(
        Rails.application.credentials[Rails.env.to_sym][:api][:transactions][:basic_authentication]
      )

      def create
        respond_to do |format|
          format.json { render_json }
          format.xml { render_xml }
        end
      end

      private

      def render_json
        result = place_transaction(:json)

        render json: result.failure? ? { error: result.error } : { success: { uuid: result.transaction.uuid } }
      end

      def render_xml
        result = place_transaction(:xml)

        render xml: [result.failure? ? { error: result.error } : { success: { uuid: result.transaction.uuid } }]
      end

      def place_transaction(format)
        Transactions::Place.call(body: request.body.read, format: format)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/concerns/collectionable.rb
# frozen_string_literal: true

module Collectionable
  def wrap_in_view_models(view_model_klass, collection)
    Kaminari.paginate_array(
      view_model_klass.collection(collection, view_context),
      total_count: collection.total_count
    ).page(params[:page])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :authenticate_admin!

  def index; end
end

app/controllers/merchant_customizations_controller.rb
# frozen_string_literal: true

# would be placed in admin folder
class MerchantCustomizationsController < ApplicationController
  before_action :authenticate_admin!
  before_action :load_merchant

  def new
    @customization = MerchantCustomization.new(merchant: @merchant)
  end

  def create
    @customization = MerchantCustomization.new(
      merchant_customization_params.merge(merchant: @merchant)
    )

    if @customization.update
      redirect_to merchant_path(@merchant), notice: 'successfully updated'
    else
      respond_with @customization
    end
  end

  private

  def load_merchant
    @merchant = Merchant.find(params[:id])
  end

  def merchant_customization_params
    params.require(:merchant_customization).permit(:name, :description, :email, :status)
  end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

# would be placed in admin folder
class MerchantsController < ApplicationController
  include Collectionable

  before_action :authenticate_admin!
  before_action :load_merchant, only: %i[show destroy]

  def index
    @merchants = Merchant.order(id: :desc).page(params[:page])
  end

  def show; end

  def destroy
    result = Merchants::Destroy.call(merchant: @merchant)

    if result.success?
      respond_with @merchant
    else
      redirect_to({ action: :show }, alert: result.error)
    end
  end

  private

  def load_merchant
    @merchant = Merchant.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

# would be placed in admin folder
class TransactionsController < ApplicationController
  include Collectionable

  before_action :authenticate_admin!

  def index
    transactions = Transaction::Base.order(created_at: :desc).page(params[:page])

    @transactions = wrap_in_view_models(TransactionView, transactions)
  end

  def show
    transaction = Transaction::Base.find(params[:id])

    @transaction = TransactionView.new(transaction, view_context)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.slim
| Hello, glad to see you!

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Acquiring
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      - if admin_signed_in?
        = render 'shared/header'
      .row.justify-content-center
        - flash.each do |type, message|
          .alert.text-center.col-6 class=(type == 'notice' ? 'alert-success' : 'alert-danger') = message
      = yield

app/views/merchant_customizations/new.html.slim
h1 Merchant customization

= semantic_form_for @customization, url: merchant_customizations_path(id: params[:id]) do |form_builder|
  = form_builder.inputs :merchant_customization_details do
    = form_builder.input :name, input_html: { value: @merchant.name }
    = form_builder.input :status, as: :select, collection: @merchant.class.statuses.keys, selected: @merchant.status
    = form_builder.input :description, input_html: { value: @merchant.description }
    = form_builder.input :email, input_html: { value: @merchant.email }

  = form_builder.actions do
    = form_builder.action :submit, label: 'Update', button_html: { class: 'btn btn-primary' }
    = form_builder.action :cancel, label: 'Cancel', button_html: { class: 'btn btn-danger' }

app/views/merchants/index.html.slim
table.table.table-striped
  thead
    tr
      th Name
      th Email
      th Status
  tbody
    - @merchants.each do |merchant|
      tr
        td = link_to merchant.name, merchant_path(merchant.id)
        td = merchant.email
        td = merchant.status

= paginate @merchants

app/views/merchants/show.html.slim
h1 Information about the merchant

table.table.table-bordered
  tr
    th Name
    td = @merchant.name
  tr
    th Type
    td = @merchant.email
  tr
    th Status
    td = @merchant.status
  tr
    th Total transaction sum
    td = @merchant.total_transaction_sum

= link_to 'Edit', new_merchant_customization_path(id: @merchant), class: 'btn btn-outline-dark me-2'
= link_to 'Destroy', merchant_path(@merchant), method: :delete, class: 'btn btn-outline-danger'

app/views/shared/_header.html.slim
ul.nav.nav-pills.mb-3.mt-3
  li.nav-item
    = link_to 'Home', root_path, class: "nav-link #{ 'active' if controller_name == 'home' }"
  li.nav-item
    = link_to 'Merchants', merchants_path, class: "nav-link #{ 'active' if controller_name == 'merchants' }"
  li.nav-item
    = link_to 'Transactions', transactions_path, class: "nav-link #{ 'active' if controller_name == 'transactions' }"

app/views/transactions/index.html.slim
table.table.table-striped
  thead
    tr
      th UUID
      th Type
      th Status
  tbody
    - @transactions.each do |transaction|
      tr
        td = link_to transaction.uuid, transaction_path(transaction.id)
        td = transaction.type
        td = transaction.status

= paginate @transactions

app/views/transactions/show.html.slim
h1 Information about the transaction

table.table.table-bordered
  tr
    th UUID
    td = @transaction.uuid
  tr
    th Type
    td = @transaction.type
  tr
    th Status
    td = @transaction.status
  tr
    th Creation date
    td = @transaction.created_at
  tr
    th History
    td = @transaction.history